### ISSUE TITLE
Passing arguments as array will return an array with the `@` string

### ISSUE THREAD

**Issue by leroy0211** [leroy0211/Slim-Container-Builder#2]
```yml
services:
  serializer.encoder.xml:
    class: 'Symfony\Component\Serializer\Encoder\XmlEncoder'

  serializer.encoder.json:
    class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'

  serializer.normalizer.object:
    class: 'Symfony\Component\Serializer\Normalizer\ObjectNormalizer'

  serializer:
    class: 'Symfony\Component\Serializer\Serializer'
    arguments:
      - ['@serializer.normalizer.object']
      - ['@serializer.encoder.json']
``` 

This will return the `Serializer` class with an array of a string.
